# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart.Foundation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart.Foundation


  pod 'Firebase/Core'
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod 'Firebase/Auth'
  pod 'TwitterKit'
  pod 'FacebookLogin'

end
